config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f/100
    sprintf("%.2f", price_in_dollars)
  end

  has_many :reviews, dependent: :destroy
  has_many :users, :through => :reviews
  belongs_to :user

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :comment, :presence => true
  validates :comment, length: { minimum: 2 }
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :products, :through => :reviews
  has_many :products
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :ensure_logged_in, :except => [:show, :index]

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%").page(params[:page])
    else
      Product.order('products.created_at DESC').page(params[:page])
    end

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @review } # render json for that object
    end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :ensure_logged_in, :only => [:create, :destroy, :edit, :update]
  before_action :load_product


  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params) # @product comes from the load_product
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), :notice => "Review created successfully" }
        format.js {} #looks for reviews/create.js.erb
        format.json { render json: @review, include: :user } # render json for that object # you can do :user because a review belongs to a user
      else
        format.html { render 'products/show', :alert => "Oops! Something went wrong!"  }
        format.js {}
        format.json { render json: @review } # render json for that object
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # we don't need to instantiate a user object
    # because we are only logging in, not creating
    # a new user
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) #if both of these are true
      session[:user_id] = user.id #create a key-value pair in the sessions hash, with a session key :user_id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

  <%= yield %>

    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>.
        <p><%= link_to "Add product", new_product_path %></p> <p><%= link_to "Log out", session_path("current"), :method => :delete %></p>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </p>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

<% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price_in_cents %>
    <%= f.text_field :price_in_cents %>
  </p>
  <%= f.submit "Save product" %>

<% end %>

app/views/products/_product.html.erb
<h2><%= link_to product.name, product_path(product) %></h2>
<p><%= product.formatted_price %></p>
<p><%= truncate(product.description, length: 100) %></p>

app/views/products/_review_form_errors.html.erb
<% @review.errors.full_messages.each do |error| %>
  <div class="alert">
    <%= error %>
  </div>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <p>
  <%= review.comment %>
  <% if review.user != nil %> <br />
    <em> by <%= review.user.name %></em>
    Added on: <%= review.created_at %>
  <% end %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit a product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<h1>All Products</h1>

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>

<script type="text/javascript">

</script>

app/views/products/index.js.erb
$('#products').append("<%= j(render @products) %>");
$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.formatted_price %></p>
<p><%= @product.description %></p>
<p>Created by <%= @product.user.name %></p>

<% if session[:user_id] == @product.user_id %>
<p><%= link_to "Edit product", edit_product_path(@product) %></p>
<% end %>

<% if current_user %>
  <h3>Reviews</h3>
  <div id="review-list">
    <%= render :partial => "reviews" %>
  </div>


  <h4>Give your own review!</h4>
  <%= form_for([@product, @review]) do |f| %>

    <div id="review-form-errors">
    </div>

    <div id="text-field">
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to 'log in', new_session_path %> to add a review or edit this product.</p>
<% end %>

<script type="text/javascript">
  $(function() {
    $('#new_review')
      .on('ajax:beforeSend', function() {
        $("input[type='submit']").val("Saving...").attr("disabled", "disabled");
      })
      .on('ajax:complete', function() {
        $("input[type='submit']").val("Create Review").removeAttr('disabled');
      });
  });
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
  $('#review-form-errors').html('<%= j(render :partial => "/products/review_form_errors") %>')
<% else %>
  $('#review-form-errors').html('')
  $('#review-list').html('<%= j(render :partial => "/products/reviews") %>')
  $('#new_review')[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
  <p>
    <%= @review.comment %>
    <% if @review.user != nil %><br />
      <em> by <%= @review.user.name %></em>
      Added on: <%= @review.created_at %>
      <% end %>
    </p>
  </a>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
        <li><% message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field"%>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>